config/routes.rb
Rails.application.routes.draw do
 resources :tasks do
  member do
    
  end
end
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_path, notice: 'タスクが追加されました。'
    else
      render :new
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクが更新されました"
    else
      render :edit
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: "タスクが削除されました"
  end

  
  private

  # Strong Parameters: 許可するパラメータを指定
  def task_params
    params.require(:task).permit(:title, :details, :deadline, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskToDo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>タスクを編集</h1>

<%= form_with model: @task, local: true do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "エラー") %> が発生しました:</h2>
      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="display: flex; align-items: center; margin-bottom: 10px;">
    <%= form.label :title, "タイトル", style: "width: 80px; margin-right: 10px;" %>
    <%= form.text_field :title, style: "flex: 1; max-width: 300px;" %>
  </div>

  <div style="display: flex; align-items: center; margin-bottom: 10px;">
    <%= form.label :details, "詳細", style: "width: 80px; margin-right: 10px;" %>
    <%= form.text_area :details, size: "30x5", style: "flex: 1; max-width: 300px;" %>
  </div>

  <div style="display: flex; align-items: center; margin-bottom: 10px;">
    <%= form.label :deadline, "作成日", style: "width: 80px; margin-right: 10px;" %>
    <%= form.date_select :deadline, start_year: Date.today.year, end_year: Date.today.year + 5, 
                         month_names: ["", "1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"] %>
  </div>

  <div style="display: flex; align-items: center; margin-bottom: 10px;">
    <%= form.label :status, "状態", style: "width: 80px; margin-right: 10px;" %>
    <%= form.select :status, options_for_select([["未完了", "未完了"], ["進行中", "進行中"], ["完了", "完了"]], @task.status), style: "flex: 1; max-width: 150px;" %>
  </div>

  <div>
    <%= form.submit "更新する" %>
  </div>
<% end %>

<%= link_to '戻る', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<%= link_to '新しいタスクを追加', new_task_path, class: 'btn' %>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>詳細</th>
      <th>作成日</th>
      <th>状態</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.details %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status %></td>
        <td>
          <%= link_to '編集', edit_task_path(task), class: 'btn' %>
          <%= button_to '削除', task_path(task), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
          
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @tasks.empty? %>
  <p>タスクがありません。</p>
<% end %>

app/views/tasks/new.html.erb
<h1>新しいタスクを追加</h1>

<%= form_with model: @task, local: true do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="display: flex; align-items: center; margin-bottom: 10px;">
    <%= form.label :title, "タイトル", style: "width: 80px; margin-right: 10px;" %>
    <%= form.text_field :title, style: "flex: 1; max-width: 300px;" %>
  </div>

  <div style="display: flex; align-items: center; margin-bottom: 10px;">
    <%= form.label :details, "詳細", style: "width: 80px; margin-right: 10px;" %>
    <%= form.text_area :details, size: "30x5", style: "flex: 1; max-width: 300px;" %>
  </div>

  <div style="display: flex; align-items: center; margin-bottom: 10px;">
    <%= form.label :deadline, "作成日", style: "width: 80px; margin-right: 10px;" %>
    <%= form.date_select :deadline, start_year: Date.today.year, end_year: Date.today.year + 5, include_blank: true, 
                         month_names: ["", "1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
                         day_names: ["", "1日", "2日", "3日", "4日", "5日", "6日", "7日", "8日", "9日", "10日", "11日", "12日", "13日", "14日", "15日", "16日", "17日", "18日", "19日", "20日", "21日", "22日", "23日", "24日", "25日", "26日", "27日", "28日", "29日", "30日", "31日"] %>
  </div>

  <div style="display: flex; align-items: center; margin-bottom: 10px;">
    <%= form.label :status, "状態", style: "width: 80px; margin-right: 10px;" %>
    <%= form.select :status, options_for_select([["未完了", "未完了"], ["進行中", "進行中"], ["完了", "完了"]]), style: "flex: 1; max-width: 150px;" %>
  </div>

  <div>
    <%= form.submit "タスクを追加" %>
  </div>
<% end %>

<%= link_to '戻る', tasks_path %>